package com.example.macos.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BLUE_TOOTH_DATA".
 */
public class BlueToothData {

    private String Id;
    private Integer RoadId;
    private String DateTimeLoging;
    private String Latitude;
    private String Longitude;
    private Double ZaxisValue;
    private String UserLoging;

    public BlueToothData() {
    }

    public BlueToothData(String Id, Integer RoadId, String DateTimeLoging, String Latitude, String Longitude, Double ZaxisValue, String UserLoging) {
        this.Id = Id;
        this.RoadId = RoadId;
        this.DateTimeLoging = DateTimeLoging;
        this.Latitude = Latitude;
        this.Longitude = Longitude;
        this.ZaxisValue = ZaxisValue;
        this.UserLoging = UserLoging;
    }

    public String getId() {
        return Id;
    }

    public void setId(String Id) {
        this.Id = Id;
    }

    public Integer getRoadId() {
        return RoadId;
    }

    public void setRoadId(Integer RoadId) {
        this.RoadId = RoadId;
    }

    public String getDateTimeLoging() {
        return DateTimeLoging;
    }

    public void setDateTimeLoging(String DateTimeLoging) {
        this.DateTimeLoging = DateTimeLoging;
    }

    public String getLatitude() {
        return Latitude;
    }

    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

    public String getLongitude() {
        return Longitude;
    }

    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

    public Double getZaxisValue() {
        return ZaxisValue;
    }

    public void setZaxisValue(Double ZaxisValue) {
        this.ZaxisValue = ZaxisValue;
    }

    public String getUserLoging() {
        return UserLoging;
    }

    public void setUserLoging(String UserLoging) {
        this.UserLoging = UserLoging;
    }

}
