package com.example.macos.database;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BLUE_TOOTH_DATA".
 */
public class BlueToothData {

    private Long ID;
    private String inputID;
    private String time;
    private Double latValue;
    private Double longValue;
    private Long zValue;
    private Boolean isUploaded;

    public BlueToothData() {
    }

    public BlueToothData(Long ID) {
        this.ID = ID;
    }

    public BlueToothData(Long ID, String inputID, String time, Double latValue, Double longValue, Long zValue, Boolean isUploaded) {
        this.ID = ID;
        this.inputID = inputID;
        this.time = time;
        this.latValue = latValue;
        this.longValue = longValue;
        this.zValue = zValue;
        this.isUploaded = isUploaded;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public String getInputID() {
        return inputID;
    }

    public void setInputID(String inputID) {
        this.inputID = inputID;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Double getLatValue() {
        return latValue;
    }

    public void setLatValue(Double latValue) {
        this.latValue = latValue;
    }

    public Double getLongValue() {
        return longValue;
    }

    public void setLongValue(Double longValue) {
        this.longValue = longValue;
    }

    public Long getZValue() {
        return zValue;
    }

    public void setZValue(Long zValue) {
        this.zValue = zValue;
    }

    public Boolean getIsUploaded() {
        return isUploaded;
    }

    public void setIsUploaded(Boolean isUploaded) {
        this.isUploaded = isUploaded;
    }

    @Override
    public String toString() {
        return "BlueToothData{" +
                "ID=" + ID +
                ", inputID='" + inputID + '\'' +
                ", time='" + time + '\'' +
                ", latValue=" + latValue +
                ", longValue=" + longValue +
                ", zValue=" + zValue +
                ", isUploaded=" + isUploaded +
                '}';
    }
}
