package com.example.macos.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataDaoConfig;
    private final DaoConfig roadInformationDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig dataTypeItemDaoConfig;
    private final DaoConfig blueToothDataDaoConfig;

    private final BlueToothDataDao blueToothDataDao;
    private final DataDao dataDao;
    private final RoadInformationDao roadInformationDao;
    private final ItemDao itemDao;
    private final DataTypeItemDao dataTypeItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataDaoConfig = daoConfigMap.get(DataDao.class).clone();
        dataDaoConfig.initIdentityScope(type);

        roadInformationDaoConfig = daoConfigMap.get(RoadInformationDao.class).clone();
        roadInformationDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        dataTypeItemDaoConfig = daoConfigMap.get(DataTypeItemDao.class).clone();
        dataTypeItemDaoConfig.initIdentityScope(type);

        blueToothDataDaoConfig = daoConfigMap.get(BlueToothDataDao.class).clone();
        blueToothDataDaoConfig.initIdentityScope(type);

        dataDao = new DataDao(dataDaoConfig, this);
        roadInformationDao = new RoadInformationDao(roadInformationDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        dataTypeItemDao = new DataTypeItemDao(dataTypeItemDaoConfig, this);
        blueToothDataDao = new BlueToothDataDao(blueToothDataDaoConfig, this);


        registerDao(Data.class, dataDao);
        registerDao(RoadInformation.class, roadInformationDao);
        registerDao(Item.class, itemDao);
        registerDao(DataTypeItem.class, dataTypeItemDao);
        registerDao(BlueToothData.class, blueToothDataDao);
    }

    public void clear() {
        dataDaoConfig.getIdentityScope().clear();
        roadInformationDaoConfig.getIdentityScope().clear();
        itemDaoConfig.getIdentityScope().clear();
        dataTypeItemDaoConfig.getIdentityScope().clear();
        blueToothDataDaoConfig.getIdentityScope().clear();
    }

    public DataDao getDataDao() {
        return dataDao;
    }

    public RoadInformationDao getRoadInformationDao() {
        return roadInformationDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public DataTypeItemDao getDataTypeItemDao() {
        return dataTypeItemDao;
    }

    public BlueToothDataDao getBlueToothDataDao() {
        return blueToothDataDao;
    }
}
