package com.example.macos.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "DATA".
 */
public class Data {

    private Long ID;
    private String input;
    private Boolean isUploaded = false;

    public Data() {
    }

    public Data(Long ID) {
        this.ID = ID;
    }

    public Data(Long ID, String input, Boolean isUploaded) {
        this.ID = ID;
        this.input = input;
        this.isUploaded = isUploaded;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public String getInput() {
        return input;
    }

    public void setInput(String input) {
        this.input = input;
    }

    public Boolean getIsUploaded() {
        return isUploaded;
    }

    public void setIsUploaded(Boolean isUploaded) {
        this.isUploaded = isUploaded;
    }

}
