package com.example.macos.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DATA".
 */
public class Data {

    private Long ID;
    private String input;

    public Data() {
    }

    public Data(Long ID) {
        this.ID = ID;
    }

    public Data(Long ID, String input) {
        this.ID = ID;
        this.input = input;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public String getInput() {
        return input;
    }

    public void setInput(String input) {
        this.input = input;
    }

}
