package com.example.macos.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "POSITION_DATA".
 */
public class PositionData {

    private String Id;
    private String UserName;
    private String LogTime;
    private String Lattitude;
    private String Longitude;

    public PositionData() {
    }

    public PositionData(String Id, String UserName, String LogTime, String Lattitude, String Longitude) {
        this.Id = Id;
        this.UserName = UserName;
        this.LogTime = LogTime;
        this.Lattitude = Lattitude;
        this.Longitude = Longitude;
    }

    public String getId() {
        return Id;
    }

    public void setId(String Id) {
        this.Id = Id;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getLogTime() {
        return LogTime;
    }

    public void setLogTime(String LogTime) {
        this.LogTime = LogTime;
    }

    public String getLattitude() {
        return Lattitude;
    }

    public void setLattitude(String Lattitude) {
        this.Lattitude = Lattitude;
    }

    public String getLongitude() {
        return Longitude;
    }

    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

}
