package com.example.macos.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ROAD_INFORMATION".
 */
public class RoadInformation {

    private Long ID;
    private String MaDuong;
    private String TenDuong;
    private String TuyenSo;
    private String TuyenNhanhSo;
    private String CapDuong;
    private Integer MaDonViQuanLy;
    private Integer TuCotKm;
    private Integer DenCotKm;
    private String ViDo;
    private String KinhDo;
    private Integer ChieuDai;
    private String NgayDieuChinhCotKm;
    private String ThoiDiemCapNhap;
    private Integer MaTinh;
    private Integer MaThanhPho;
    private String LoadLanDuong;
    private Integer NamXayDung;
    private Double HanhLangDuongBo;
    private String LoaiKetCauDuong;
    private Integer SoLanXeCoGioi;
    private Double ChieuRongLanXeCoGioi;
    private String LoaiMatDuongLanXeCoGioi;
    private Integer SoLanxeThoSo;
    private String LoaiMatDuongLanXeThoSo;
    private Double ChieuRongLanXeThoSo;
    private Double ChieuRongDuongXeChay;
    private Double ChieuRongMatDuong;
    private String LeDuong;
    private Double ChieuRongLeDuong;
    private String ViaHe;
    private Double ChieuRongViaHe;
    private String LoaiViaHe;
    private Double ChieuRongThoatNuoc;
    private Double TocDoThietKe;
    private String LoaiDiaHinh;
    private String LoaiNenDuong;

    public RoadInformation() {
    }

    public RoadInformation(Long ID) {
        this.ID = ID;
    }

    @Override
    public String toString() {
        return "RoadInformation{" +
                "ID=" + ID +
                ",\n MaDuong='" + MaDuong + '\'' +
                ",\n TenDuong='" + TenDuong + '\'' +
                ",\n TuyenSo='" + TuyenSo + '\'' +
                ",\n TuyenNhanhSo='" + TuyenNhanhSo + '\'' +
                ",\n CapDuong='" + CapDuong + '\'' +
                ",\n MaDonViQuanLy=" + MaDonViQuanLy +
                ",\n TuCotKm=" + TuCotKm +
                ",\n DenCotKm=" + DenCotKm +
                ",\n ViDo='" + ViDo + '\'' +
                ",\n KinhDo='" + KinhDo + '\'' +
                ",\n ChieuDai=" + ChieuDai +
                ",\n NgayDieuChinhCotKm='" + NgayDieuChinhCotKm + '\'' +
                ",\n ThoiDiemCapNhap='" + ThoiDiemCapNhap + '\'' +
                ",\n MaTinh=" + MaTinh +
                ",\n MaThanhPho=" + MaThanhPho +
                ",\n LoadLanDuong='" + LoadLanDuong + '\'' +
                ",\n NamXayDung=" + NamXayDung +
                ",\n HanhLangDuongBo=" + HanhLangDuongBo +
                ",\n LoaiKetCauDuong='" + LoaiKetCauDuong + '\'' +
                ",\n SoLanXeCoGioi=" + SoLanXeCoGioi +
                ",\n ChieuRongLanXeCoGioi=" + ChieuRongLanXeCoGioi +
                ",\n LoaiMatDuongLanXeCoGioi='" + LoaiMatDuongLanXeCoGioi + '\'' +
                ",\n SoLanxeThoSo=" + SoLanxeThoSo +
                ",\n LoaiMatDuongLanXeThoSo='" + LoaiMatDuongLanXeThoSo + '\'' +
                ",\n ChieuRongLanXeThoSo=" + ChieuRongLanXeThoSo +
                ",\n ChieuRongDuongXeChay=" + ChieuRongDuongXeChay +
                ",\n ChieuRongMatDuong=" + ChieuRongMatDuong +
                ",\n LeDuong='" + LeDuong + '\'' +
                ",\n ChieuRongLeDuong=" + ChieuRongLeDuong +
                ",\n ViaHe='" + ViaHe + '\'' +
                ",\n ChieuRongViaHe=" + ChieuRongViaHe +
                ",\n LoaiViaHe='" + LoaiViaHe + '\'' +
                ",\n ChieuRongThoatNuoc=" + ChieuRongThoatNuoc +
                ",\n TocDoThietKe=" + TocDoThietKe +
                ",\n LoaiDiaHinh='" + LoaiDiaHinh + '\'' +
                ",\n LoaiNenDuong='" + LoaiNenDuong + '\'' +
                '}';
    }

    public RoadInformation(Long ID, String MaDuong, String TenDuong, String TuyenSo, String TuyenNhanhSo, String CapDuong, Integer MaDonViQuanLy, Integer TuCotKm, Integer DenCotKm, String ViDo, String KinhDo, Integer ChieuDai, String NgayDieuChinhCotKm, String ThoiDiemCapNhap, Integer MaTinh, Integer MaThanhPho, String LoadLanDuong, Integer NamXayDung, Double HanhLangDuongBo, String LoaiKetCauDuong, Integer SoLanXeCoGioi, Double ChieuRongLanXeCoGioi, String LoaiMatDuongLanXeCoGioi, Integer SoLanxeThoSo, String LoaiMatDuongLanXeThoSo, Double ChieuRongLanXeThoSo, Double ChieuRongDuongXeChay, Double ChieuRongMatDuong, String LeDuong, Double ChieuRongLeDuong, String ViaHe, Double ChieuRongViaHe, String LoaiViaHe, Double ChieuRongThoatNuoc, Double TocDoThietKe, String LoaiDiaHinh, String LoaiNenDuong) {
        this.ID = ID;
        this.MaDuong = MaDuong;
        this.TenDuong = TenDuong;
        this.TuyenSo = TuyenSo;
        this.TuyenNhanhSo = TuyenNhanhSo;
        this.CapDuong = CapDuong;
        this.MaDonViQuanLy = MaDonViQuanLy;
        this.TuCotKm = TuCotKm;
        this.DenCotKm = DenCotKm;
        this.ViDo = ViDo;
        this.KinhDo = KinhDo;
        this.ChieuDai = ChieuDai;
        this.NgayDieuChinhCotKm = NgayDieuChinhCotKm;
        this.ThoiDiemCapNhap = ThoiDiemCapNhap;
        this.MaTinh = MaTinh;
        this.MaThanhPho = MaThanhPho;
        this.LoadLanDuong = LoadLanDuong;
        this.NamXayDung = NamXayDung;
        this.HanhLangDuongBo = HanhLangDuongBo;
        this.LoaiKetCauDuong = LoaiKetCauDuong;
        this.SoLanXeCoGioi = SoLanXeCoGioi;
        this.ChieuRongLanXeCoGioi = ChieuRongLanXeCoGioi;
        this.LoaiMatDuongLanXeCoGioi = LoaiMatDuongLanXeCoGioi;
        this.SoLanxeThoSo = SoLanxeThoSo;
        this.LoaiMatDuongLanXeThoSo = LoaiMatDuongLanXeThoSo;
        this.ChieuRongLanXeThoSo = ChieuRongLanXeThoSo;
        this.ChieuRongDuongXeChay = ChieuRongDuongXeChay;
        this.ChieuRongMatDuong = ChieuRongMatDuong;
        this.LeDuong = LeDuong;
        this.ChieuRongLeDuong = ChieuRongLeDuong;
        this.ViaHe = ViaHe;
        this.ChieuRongViaHe = ChieuRongViaHe;
        this.LoaiViaHe = LoaiViaHe;
        this.ChieuRongThoatNuoc = ChieuRongThoatNuoc;
        this.TocDoThietKe = TocDoThietKe;
        this.LoaiDiaHinh = LoaiDiaHinh;
        this.LoaiNenDuong = LoaiNenDuong;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public String getMaDuong() {
        return MaDuong;
    }

    public void setMaDuong(String MaDuong) {
        this.MaDuong = MaDuong;
    }

    public String getTenDuong() {
        return TenDuong;
    }

    public void setTenDuong(String TenDuong) {
        this.TenDuong = TenDuong;
    }

    public String getTuyenSo() {
        return TuyenSo;
    }

    public void setTuyenSo(String TuyenSo) {
        this.TuyenSo = TuyenSo;
    }

    public String getTuyenNhanhSo() {
        return TuyenNhanhSo;
    }

    public void setTuyenNhanhSo(String TuyenNhanhSo) {
        this.TuyenNhanhSo = TuyenNhanhSo;
    }

    public String getCapDuong() {
        return CapDuong;
    }

    public void setCapDuong(String CapDuong) {
        this.CapDuong = CapDuong;
    }

    public Integer getMaDonViQuanLy() {
        return MaDonViQuanLy;
    }

    public void setMaDonViQuanLy(Integer MaDonViQuanLy) {
        this.MaDonViQuanLy = MaDonViQuanLy;
    }

    public Integer getTuCotKm() {
        return TuCotKm;
    }

    public void setTuCotKm(Integer TuCotKm) {
        this.TuCotKm = TuCotKm;
    }

    public Integer getDenCotKm() {
        return DenCotKm;
    }

    public void setDenCotKm(Integer DenCotKm) {
        this.DenCotKm = DenCotKm;
    }

    public String getViDo() {
        return ViDo;
    }

    public void setViDo(String ViDo) {
        this.ViDo = ViDo;
    }

    public String getKinhDo() {
        return KinhDo;
    }

    public void setKinhDo(String KinhDo) {
        this.KinhDo = KinhDo;
    }

    public Integer getChieuDai() {
        return ChieuDai;
    }

    public void setChieuDai(Integer ChieuDai) {
        this.ChieuDai = ChieuDai;
    }

    public String getNgayDieuChinhCotKm() {
        return NgayDieuChinhCotKm;
    }

    public void setNgayDieuChinhCotKm(String NgayDieuChinhCotKm) {
        this.NgayDieuChinhCotKm = NgayDieuChinhCotKm;
    }

    public String getThoiDiemCapNhap() {
        return ThoiDiemCapNhap;
    }

    public void setThoiDiemCapNhap(String ThoiDiemCapNhap) {
        this.ThoiDiemCapNhap = ThoiDiemCapNhap;
    }

    public Integer getMaTinh() {
        return MaTinh;
    }

    public void setMaTinh(Integer MaTinh) {
        this.MaTinh = MaTinh;
    }

    public Integer getMaThanhPho() {
        return MaThanhPho;
    }

    public void setMaThanhPho(Integer MaThanhPho) {
        this.MaThanhPho = MaThanhPho;
    }

    public String getLoadLanDuong() {
        return LoadLanDuong;
    }

    public void setLoadLanDuong(String LoadLanDuong) {
        this.LoadLanDuong = LoadLanDuong;
    }

    public Integer getNamXayDung() {
        return NamXayDung;
    }

    public void setNamXayDung(Integer NamXayDung) {
        this.NamXayDung = NamXayDung;
    }

    public Double getHanhLangDuongBo() {
        return HanhLangDuongBo;
    }

    public void setHanhLangDuongBo(Double HanhLangDuongBo) {
        this.HanhLangDuongBo = HanhLangDuongBo;
    }

    public String getLoaiKetCauDuong() {
        return LoaiKetCauDuong;
    }

    public void setLoaiKetCauDuong(String LoaiKetCauDuong) {
        this.LoaiKetCauDuong = LoaiKetCauDuong;
    }

    public Integer getSoLanXeCoGioi() {
        return SoLanXeCoGioi;
    }

    public void setSoLanXeCoGioi(Integer SoLanXeCoGioi) {
        this.SoLanXeCoGioi = SoLanXeCoGioi;
    }

    public Double getChieuRongLanXeCoGioi() {
        return ChieuRongLanXeCoGioi;
    }

    public void setChieuRongLanXeCoGioi(Double ChieuRongLanXeCoGioi) {
        this.ChieuRongLanXeCoGioi = ChieuRongLanXeCoGioi;
    }

    public String getLoaiMatDuongLanXeCoGioi() {
        return LoaiMatDuongLanXeCoGioi;
    }

    public void setLoaiMatDuongLanXeCoGioi(String LoaiMatDuongLanXeCoGioi) {
        this.LoaiMatDuongLanXeCoGioi = LoaiMatDuongLanXeCoGioi;
    }

    public Integer getSoLanxeThoSo() {
        return SoLanxeThoSo;
    }

    public void setSoLanxeThoSo(Integer SoLanxeThoSo) {
        this.SoLanxeThoSo = SoLanxeThoSo;
    }

    public String getLoaiMatDuongLanXeThoSo() {
        return LoaiMatDuongLanXeThoSo;
    }

    public void setLoaiMatDuongLanXeThoSo(String LoaiMatDuongLanXeThoSo) {
        this.LoaiMatDuongLanXeThoSo = LoaiMatDuongLanXeThoSo;
    }

    public Double getChieuRongLanXeThoSo() {
        return ChieuRongLanXeThoSo;
    }

    public void setChieuRongLanXeThoSo(Double ChieuRongLanXeThoSo) {
        this.ChieuRongLanXeThoSo = ChieuRongLanXeThoSo;
    }

    public Double getChieuRongDuongXeChay() {
        return ChieuRongDuongXeChay;
    }

    public void setChieuRongDuongXeChay(Double ChieuRongDuongXeChay) {
        this.ChieuRongDuongXeChay = ChieuRongDuongXeChay;
    }

    public Double getChieuRongMatDuong() {
        return ChieuRongMatDuong;
    }

    public void setChieuRongMatDuong(Double ChieuRongMatDuong) {
        this.ChieuRongMatDuong = ChieuRongMatDuong;
    }

    public String getLeDuong() {
        return LeDuong;
    }

    public void setLeDuong(String LeDuong) {
        this.LeDuong = LeDuong;
    }

    public Double getChieuRongLeDuong() {
        return ChieuRongLeDuong;
    }

    public void setChieuRongLeDuong(Double ChieuRongLeDuong) {
        this.ChieuRongLeDuong = ChieuRongLeDuong;
    }

    public String getViaHe() {
        return ViaHe;
    }

    public void setViaHe(String ViaHe) {
        this.ViaHe = ViaHe;
    }

    public Double getChieuRongViaHe() {
        return ChieuRongViaHe;
    }

    public void setChieuRongViaHe(Double ChieuRongViaHe) {
        this.ChieuRongViaHe = ChieuRongViaHe;
    }

    public String getLoaiViaHe() {
        return LoaiViaHe;
    }

    public void setLoaiViaHe(String LoaiViaHe) {
        this.LoaiViaHe = LoaiViaHe;
    }

    public Double getChieuRongThoatNuoc() {
        return ChieuRongThoatNuoc;
    }

    public void setChieuRongThoatNuoc(Double ChieuRongThoatNuoc) {
        this.ChieuRongThoatNuoc = ChieuRongThoatNuoc;
    }

    public Double getTocDoThietKe() {
        return TocDoThietKe;
    }

    public void setTocDoThietKe(Double TocDoThietKe) {
        this.TocDoThietKe = TocDoThietKe;
    }

    public String getLoaiDiaHinh() {
        return LoaiDiaHinh;
    }

    public void setLoaiDiaHinh(String LoaiDiaHinh) {
        this.LoaiDiaHinh = LoaiDiaHinh;
    }

    public String getLoaiNenDuong() {
        return LoaiNenDuong;
    }

    public void setLoaiNenDuong(String LoaiNenDuong) {
        this.LoaiNenDuong = LoaiNenDuong;
    }

}
